### ISSUE TITLE
Consider using `autocomplete` attributes for contact details

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/gaap-assistive-tech-research-prototype#20]
The Design System guidance advises using the `autocomplete` attribute on form fields where there's a corresponding entity to use. See for example the guidance for using [textarea for addresses](https://design-system.service.gov.uk/patterns/addresses/#use-the-autocomplete-attribute-on-a-textarea).

**Comment by NickColley** [comment]
I copy pasted these from the design system, looks like we have some examples that need updating...

**Comment by NickColley** [comment]
Will do this before tomorrow
