### ISSUE TITLE
Choosing fast-track delivery doesn’t change the price

### ISSUE THREAD

**Issue by 36degrees** [alphagov/gaap-assistive-tech-research-prototype#22]
May not be an issue, but the cost on the payment page is always £10, even if you've selected fast-track delivery for '£8.50 extra'.

**Comment by quis** [comment]
@iqbalgds can you set up a second prototype link for this?

Amount: £18.50
Description: Blue badge application fee (fast track delivery)

**Comment by iqbalgds** [comment]
@quis Done - please use this link:
https://www.payments.service.gov.uk/card_details/k5u9f81gpj2f9m4ivnfii38qo9
